import type { Metadata } from "next";
import { Providers } from "@/lib/Provider";

export const metadata: Metadata = {
  title: "Secure Next App",
  description: "Generated by create next app",
};

export default function ChildLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}